### PR TITLE
Switch to using the rpm's startup script

### PR DESCRIPTION
**Pull request by DrDaveD**
See [SOFTWARE-4357](https://opensciencegrid.atlassian.net/browse/SOFTWARE-4357)

### CODE REVIEW

**Comment by brianhlin** [comment]
Could you point me at the upstream `fn-local-squid.sh`?

Also FYI @sfiligoi @efajardo

**Comment by DrDaveD** [comment]
It's a quite big and complicated script, [here](https://gitlab.cern.ch/frontier/tarballs/frontier-squid4/-/blob/master/frontier-squid-utils/bin/fn-local-squid.sh.proto), that implements most of the add-on functionality of frontier-squid over squid.

**Review by brianhlin — APPROVED** [review]
This looks fine to me. Last call @efajardo @sfiligoi

**Comment by efajardo** [comment]
Well if it has same functionality I am fine with it.

**Pull request merged**
