### PR TITLE
Fixing the right value for squid cache dir (SOFTWARE-4054)

### PR DESCRIPTION
**Pull request by efajardo**
I tested this and the nubmer should be 2 according to the [squid doc](https://twiki.cern.ch/twiki/bin/view/Frontier/InstallSquid#Moving_disk_cache_and_logs_to_a)

### CODE REVIEW

**Comment by sfiligoi** [comment]
The upstream documentation is conflicting; it is showing 3 here:
https://twiki.cern.ch/twiki/bin/view/Frontier/InstallSquid#Configuration

**Comment by efajardo** [comment]
@sfiligoi that is for the size of the cache not for the location

**Comment by sfiligoi** [comment]
And SQUID_CACHE_DISK was supposed to be the cachee size, not location.
Analogous to SQUID_CACHE_MEM.

**Comment by sfiligoi** [comment]
I think your commit is wrong.
You want to add another env variable for the disk location,
not change the semantics of the existing one, which is "How big should my disk cache be"

**Comment by sfiligoi** [comment]
BTW: Why do you even need to specify a disk location?
In a container you are free to mount any external storage to any directory path, so just mount it to where the squid expects it to be.
(still think the above commit is invalid)

**Review by sfiligoi — CHANGES_REQUESTED** [review]
I don't think you want to change the semantics of SQUID_CACHE_DISK env variable.
It is supposed to be the size of the disk cache, so the old behavior was correct.

**Review by sfiligoi — APPROVED** [review]
Looks good now.

**Comment by brianhlin** [comment]
> BTW: Why do you even need to specify a disk location?
In a container you are free to mount any external storage to any directory path, so just mount it to where the squid expects it to be.
(still think the above commit is invalid)

I'm wondering the same thing. If the user sets this env var to something else, doesn't squid fail?

**Comment by sfiligoi** [comment]
@brianhlin Why would it fail?
As long as that area exists, it will work fine.

Still think it is not essential, but I am not objecting to it.

**Comment by brianhlin** [comment]
IIRC, this was failing for Edgar without this change but I could have the details wrong. But if there's the possibility of user setting this to a non-existent dir and causing a startup failure, why can't we just prescribe the disk location in the container? We can just tell users that if they want a persistent cache between images, they need to mount a host dir into `/var/cache/squid/`, like how Apache tells users to copy files they want to serve into [/usr/local/apache2/htdocs/](https://hub.docker.com/_/httpd/#!)

**Comment by sfiligoi** [comment]
@brianhlin  We did not have the option to change the directory path before, only the cache size.
Edgar misunderstood the semantics of the existing options.

As for "why not tell...":
Yes, it is not essential, there are other ways.

But I don't see any major reason not to have also an easy way for users to use the ENV path; they can always do it with a custom script, if they really want to.
Bottom line, I am OK with Edgar's proposed addition.

**Comment by brianhlin** [comment]
@efajardo I wish you didn't merge this with our ongoing discussion...

But why would anyone want to change the existing path? This new env var strikes me as antithetical to the idea that containers should prescribe convention, i.e. you tell users the container paths to use and giving them an option to configure one is unnecessary cruft.

**Comment by efajardo** [comment]
@brianhlin well I closed cause it was approved. But the reason I had to create this is I am running two caches (Xcache and squid) on same partition. So in order for them not to interfere with one another I had to create a directory deeper into that partition. Since we are no longer using direct mount volumes from hosts I could not mount directly that partition. So this was needed. The fact that this is something that squid provides and we provide as an option. I do nto see the big deal is not used by default. So it is there only if someone really wants to use it. I can undo the merge.

**Pull request merged**
