### PR TITLE
Use the OSG Software Base image

### PR DESCRIPTION
**Pull request by brianhlin**
@sfiligoi we've decided in the [container policy](https://github.com/opensciencegrid/technology/blob/master/docs/policy/container-release.md) that we don't want to get into the business of supporting different OSes in the OSG images so I made an OSG software base image

### CODE REVIEW

**Comment by sfiligoi** [comment]
squid-customize.sh is not executable anymore?
Have you tested that it still works?

**Comment by sfiligoi** [comment]
BTW: I see that travis is building the Dockerfile. Is the resulting image available somewhere for manual testing?

**Comment by brianhlin** [comment]
Unfortunately, no, we only push images to Docker Hub from the master branch

**Review by sfiligoi — APPROVED** [review]
Looks good. Tested on PRP, worked as expected.

**Comment by brianhlin** [comment]
@sfiligoi there should be a `development` image available shortly via Docker Hub, would you be able to install that on the PRP as well?

@timtheisen if Igor's testing goes well, then we can tag our first `stable` image \o/!

**Comment by sfiligoi** [comment]
Can confirm opensciencegrid/frontier-squid:development works fine on PRP

**Pull request merged**
