### PR TITLE
Add filebeat (requested by ATLAS) (SOFTWARE-4539)

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by DrDaveD** [comment]
By default this doesn't do anything, right?  The container user would need to bind in a configuration file?  Wouldn't it be better to give them a configuration variable to enable it, probably the name of the host to send the filebeat info to?  I suggest having the requester review this PR.

**Review by brianhlin — APPROVED** [review]
Hi @DrDaveD, for the sake of expediency we just wanted to ship the bits for the SLATE team, who will have to bind mount the filebeat and supervisor or cron config. I think from there we can take our time thinking about enabling via config variable, default configs, and what other interfaces users will need (i.e., host/port/auth info for the ES interface)

**Comment by brianhlin** [comment]
FYI @ivukotic and @muali14

**Comment by DrDaveD** [comment]
It has also been my experience that for most squid installations, it does not make sense to try to automate analyzing log information.  There's just too much data and too little variation because all the requests are coming from a local LAN.  WLCG squid operations analyzes logs for special purpose squid installations only, the reverse proxies to central servers and backup proxies, because we want to know where the requests are coming from.  I know of at least one site that fed the data into kibana, but it really wasn't very useful especially considering the large amount of resources it consumed.

**Comment by brianhlin** [comment]
That's good to keep in mind (see above @ivukotic and @muali14) but otherwise this is harmless so I'm going to go ahead and merge

**Pull request merged**
